# Generated by Django 4.0.3 on 2022-04-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_gardener_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardener',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tell us about yourself'),
        ),
    ]
