# Generated by Django 4.0.3 on 2022-04-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gardener_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defaultplant.svg', null=True, upload_to='plant_pics')),
                ('commonname', models.CharField(max_length=50)),
                ('cultivar', models.CharField(blank=True, max_length=40)),
                ('species', models.CharField(blank=True, max_length=40)),
                ('genus', models.CharField(blank=True, max_length=40)),
                ('family', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=40)),
                ('mintemp', models.CharField(blank=True, max_length=40)),
                ('maxtemp', models.CharField(blank=True, max_length=40)),
                ('lightreq', models.CharField(blank=True, max_length=40)),
                ('waterreq', models.CharField(blank=True, max_length=5)),
                ('minzone', models.CharField(blank=True, max_length=3)),
                ('maxzone', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='gardener',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='About me'),
        ),
    ]
