# Generated by Django 4.0.3 on 2022-04-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_plant_alter_gardener_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gardener',
            old_name='user_name',
            new_name='username',
        ),
    ]
