# Generated by Django 4.0.3 on 2022-04-05 15:07

import api.models.gardeners
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_name_gardener_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gardener',
            managers=[
                ('objects', api.models.gardeners.GardenerManager()),
            ],
        ),
    ]
