# Generated by Django 4.0.3 on 2022-04-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gardener_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardener',
            name='username',
            field=models.CharField(max_length=20, verbose_name='username'),
        ),
    ]
